name = "2020_dt"
description = "My simple dark theme"
license = "TODO"
homepage = "https://github.com/0xSbock/2020_dt"
min_version = "0.11.0"

[extra]


[author]
name = "Sebastian Bockholt"
homepage = "https://sbock.dev/"

#[original]
# this is not a port of an existing theme...
